export const UPDATE_CONVERSATIONS_LIST = "UPDATE_CONVERSATIONS_LIST";
export const UPDATE_FETCH_GET_MY_CONVERSATIONS_IS_RUNNING = "UPDATE_FETCH_GET_MY_CONVERSATIONS_IS_RUNNING";
export const FETCH_GET_MY_CONVERSATIONS = "FETCH_GET_MY_CONVERSATIONS";