export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const FETCH_SIGN_IN = "FETCH_SIGN_IN";
export const UPDATE_FETCH_SIGN_IN_RUNNING = "UPDATE_FETCH_SIGN_IN_RUNNING";
export const UPDATE_IS_TOKENS_EXIST = "UPDATE_IS_TOKENS_EXIST" 